import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../services/api_service.dart';

class RecipeScreen extends StatefulWidget {
  const RecipeScreen({super.key});

  @override
  State<RecipeScreen> createState() => _RecipeScreenState();
}

class _RecipeScreenState extends State<RecipeScreen> {
  final _productController = TextEditingController();
  bool _isLoading = false;
  Map<String, dynamic>? _recipeData;
  String _errorMessage = "";
  int _resetCounter = 0;

  void _clearRecipeState() {
    _productController.clear();
    setState(() {
      _resetCounter++;
      _isLoading = false;
      _recipeData = null;
      _errorMessage = "";
    });
  }

  final List<String> _quickSuggestions = [
    "Maggi Noodles",
    "Instant Oats",
    "Brown Bread",
    "Marie Gold Biscuits",
    "Corn Flakes",
    "Paneer",
  ];

  @override
  void dispose() {
    _productController.dispose();
    super.dispose();
  }

  void _generateRecipe([String? query]) async {
    final product = (query ?? _productController.text).trim();
    if (product.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter a food item or choose from quick items.'),
          backgroundColor: Color(0xFFE65100),
        ),
      );
      return;
    }

    if (query != null) {
      _productController.text = query;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = "";
      _recipeData = null;
    });

    final data = await ApiService.generateRecipe(product);

    if (mounted) {
      setState(() {
        _isLoading = false;
        if (data != null) {
          _recipeData = data;
        } else {
          _errorMessage = "Could not generate recipe at this moment. Please check your internet connection.";
        }
      });
    }
  }

  void _copyRecipeToClipboard() {
    if (_recipeData == null) return;
    final title = _recipeData?['recipeName'] ?? '';
    final time = _recipeData?['prepTime'] ?? '';
    final ings = (_recipeData?['ingredients'] as List? ?? []).map((e) => "- $e").join("\n");
    final steps = (_recipeData?['instructions'] as List? ?? []).asMap().entries.map((e) => "${e.key + 1}. ${e.value}").join("\n");
    final benefits = _recipeData?['healthBenefits'] ?? '';

    final text = """
$title ($time)

INGREDIENTS:
$ings

INSTRUCTIONS:
$steps

HEALTH BENEFIT:
$benefits

Generated by Vitahar App
""";

    Clipboard.setData(ClipboardData(text: text));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Recipe copied to clipboard!'),
        backgroundColor: Color(0xFF2E7D32),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF9F7F1),
      appBar: AppBar(
        title: const Row(
          children: [
            Text('✨', style: TextStyle(fontSize: 22)),
            SizedBox(width: 8),
            Text(
              'AI Healthy Recipe Maker',
              style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black87, fontSize: 19),
            ),
          ],
        ),
        backgroundColor: Colors.white,
        elevation: 0.5,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Banner Intro
            Container(
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [Color(0xFFFF9800), Color(0xFFF57C00)],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(18),
                boxShadow: [
                  BoxShadow(
                    color: const Color(0xFFFF9800).withValues(alpha: 0.25),
                    blurRadius: 10,
                    offset: const Offset(0, 3),
                  ),
                ],
              ),
              padding: const EdgeInsets.all(18),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Row(
                    children: [
                      Icon(Icons.restaurant_menu, color: Colors.white, size: 24),
                      SizedBox(width: 8),
                      Text(
                        'Turn Packaged Foods Healthy',
                        style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                  const SizedBox(height: 6),
                  Text(
                    'Our AI chef crafts nutritious, low-sodium recipes that incorporate your favorite packaged foods safely.',
                    style: TextStyle(color: Colors.white.withValues(alpha: 0.95), fontSize: 13),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),

            // Product Input Box
            Container(
              key: ValueKey('recipe_box_$_resetCounter'),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(18),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.04),
                    blurRadius: 10,
                    offset: const Offset(0, 2),
                  ),
                ],
              ),
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  const Text(
                    'What packaged food do you want to cook with?',
                    style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Colors.black87),
                  ),
                  const SizedBox(height: 10),

                  // Search Input Row: [ Search Recipe ........ ] [ Clear ]
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: Autocomplete<String>(
                          optionsBuilder: (textVal) async {
                            if (textVal.text.length < 2) return const Iterable<String>.empty();
                            return await ApiService.fetchFoodSuggestions(textVal.text);
                          },
                          onSelected: (val) => _generateRecipe(val),
                          fieldViewBuilder: (ctx, ctrl, focus, _) {
                            if (_productController.text.isNotEmpty && ctrl.text.isEmpty) {
                              ctrl.text = _productController.text;
                            }
                            ctrl.addListener(() => _productController.text = ctrl.text);
                            return TextField(
                              controller: ctrl,
                              focusNode: focus,
                              onSubmitted: (val) => _generateRecipe(val),
                              decoration: InputDecoration(
                                hintText: 'e.g. Maggi, Instant Noodles, Oats',
                                prefixIcon: const Icon(Icons.lunch_dining_outlined, color: Colors.orange),
                                suffixIcon: ctrl.text.isNotEmpty
                                    ? IconButton(
                                        icon: const Icon(Icons.clear, size: 18, color: Colors.grey),
                                        onPressed: () {
                                          ctrl.clear();
                                          _clearRecipeState();
                                        },
                                      )
                                    : null,
                                filled: true,
                                fillColor: const Color(0xFFFBFBFB),
                                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                                contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
                              ),
                            );
                          },
                        ),
                      ),
                      const SizedBox(width: 8),
                      SizedBox(
                        height: 50,
                        child: OutlinedButton.icon(
                          onPressed: _clearRecipeState,
                          icon: const Icon(Icons.backspace_outlined, size: 18),
                          label: const Text('Clear', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                          style: OutlinedButton.styleFrom(
                            foregroundColor: const Color(0xFFD32F2F),
                            side: BorderSide(color: Colors.red.shade300, width: 1.5),
                            padding: const EdgeInsets.symmetric(horizontal: 12),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                            backgroundColor: Colors.white,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),

                  // Quick Suggestion Chips
                  Wrap(
                    spacing: 8,
                    runSpacing: 4,
                    children: _quickSuggestions.map((item) {
                      return ActionChip(
                        label: Text(item, style: const TextStyle(fontSize: 12)),
                        backgroundColor: const Color(0xFFFFF3E0),
                        side: BorderSide(color: Colors.orange.shade200),
                        onPressed: () => _generateRecipe(item),
                      );
                    }).toList(),
                  ),
                  const SizedBox(height: 14),

                  // Action Buttons: [ Generate Recipe Now ] [ Clear ]
                  Row(
                    children: [
                      Expanded(
                        flex: 3,
                        child: ElevatedButton.icon(
                          onPressed: _isLoading ? null : () => _generateRecipe(),
                          icon: _isLoading
                              ? const SizedBox(
                                  width: 18,
                                  height: 18,
                                  child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                                )
                              : const Icon(Icons.auto_awesome),
                          label: Text(
                            _isLoading ? 'AI Cooking...' : 'Generate Recipe Now',
                            style: const TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFFFF9800),
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                            elevation: 2,
                          ),
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        flex: 2,
                        child: OutlinedButton.icon(
                          onPressed: _clearRecipeState,
                          icon: const Icon(Icons.delete_sweep_outlined, size: 20),
                          label: const Text('Clear', style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
                          style: OutlinedButton.styleFrom(
                            foregroundColor: const Color(0xFFD32F2F),
                            side: BorderSide(color: Colors.red.shade300, width: 1.5),
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                            backgroundColor: Colors.white,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),

            // Error Display
            if (_errorMessage.isNotEmpty)
              Container(
                padding: const EdgeInsets.all(14),
                decoration: BoxDecoration(
                  color: const Color(0xFFFFEBEE),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.red.shade200),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.error_outline, color: Colors.red),
                    const SizedBox(width: 8),
                    Expanded(child: Text(_errorMessage, style: const TextStyle(color: Colors.red, fontSize: 13))),
                  ],
                ),
              ),

            // Recipe Card
            if (_recipeData != null) ...[
              Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: Colors.orange.shade200),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.05),
                      blurRadius: 12,
                      offset: const Offset(0, 3),
                    ),
                  ],
                ),
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          child: Text(
                            _recipeData!['recipeName'] ?? 'Healthy Recipe',
                            style: const TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFFE65100),
                            ),
                          ),
                        ),
                        IconButton(
                          icon: const Icon(Icons.copy, size: 20, color: Colors.grey),
                          tooltip: 'Copy Recipe',
                          onPressed: _copyRecipeToClipboard,
                        ),
                      ],
                    ),
                    const SizedBox(height: 6),
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                          decoration: BoxDecoration(
                            color: const Color(0xFFFFF3E0),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              const Icon(Icons.timer_outlined, size: 14, color: Color(0xFFE65100)),
                              const SizedBox(width: 4),
                              Text(
                                _recipeData!['prepTime'] ?? '15 mins',
                                style: const TextStyle(
                                  fontSize: 12,
                                  fontWeight: FontWeight.bold,
                                  color: Color(0xFFE65100),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    const Divider(height: 1),
                    const SizedBox(height: 14),

                    // Ingredients
                    const Row(
                      children: [
                        Icon(Icons.check_circle_outline, color: Color(0xFF2E7D32), size: 18),
                        SizedBox(width: 6),
                        Text(
                          'Ingredients',
                          style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF2E7D32)),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    ...((_recipeData!['ingredients'] as List? ?? []).map((ing) => Padding(
                          padding: const EdgeInsets.symmetric(vertical: 3.0),
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('• ', style: TextStyle(color: Color(0xFF2E7D32), fontWeight: FontWeight.bold, fontSize: 16)),
                              Expanded(
                                child: Text(
                                  ing.toString(),
                                  style: const TextStyle(fontSize: 14, color: Colors.black87),
                                ),
                              ),
                            ],
                          ),
                        ))),
                    const SizedBox(height: 16),
                    const Divider(height: 1),
                    const SizedBox(height: 14),

                    // Instructions
                    const Row(
                      children: [
                        Icon(Icons.format_list_numbered, color: Color(0xFF2E7D32), size: 18),
                        SizedBox(width: 6),
                        Text(
                          'Instructions',
                          style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF2E7D32)),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    ...((_recipeData!['instructions'] as List? ?? []).asMap().entries.map((entry) {
                      final stepNum = entry.key + 1;
                      final stepText = entry.value.toString();
                      return Padding(
                        padding: const EdgeInsets.symmetric(vertical: 4.0),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 22,
                              height: 22,
                              margin: const EdgeInsets.only(top: 2, right: 8),
                              decoration: const BoxDecoration(
                                color: Color(0xFFE8F5E9),
                                shape: BoxShape.circle,
                              ),
                              alignment: Alignment.center,
                              child: Text(
                                '$stepNum',
                                style: const TextStyle(
                                  color: Color(0xFF2E7D32),
                                  fontWeight: FontWeight.bold,
                                  fontSize: 12,
                                ),
                              ),
                            ),
                            Expanded(
                              child: Text(
                                stepText,
                                style: const TextStyle(fontSize: 14, color: Colors.black87, height: 1.4),
                              ),
                            ),
                          ],
                        ),
                      );
                    })),
                    const SizedBox(height: 16),

                    // Health Benefit Banner
                    if (_recipeData!['healthBenefits'] != null)
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: const Color(0xFFE8F5E9),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: const Color(0xFFC8E6C9)),
                        ),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text('💡', style: TextStyle(fontSize: 18)),
                            const SizedBox(width: 8),
                            Expanded(
                              child: RichText(
                                text: TextSpan(
                                  style: const TextStyle(color: Color(0xFF1B5E20), fontSize: 13),
                                  children: [
                                    const TextSpan(text: 'Health Benefit: ', style: TextStyle(fontWeight: FontWeight.bold)),
                                    TextSpan(text: _recipeData!['healthBenefits'].toString()),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
            ],
          ],
        ),
      ),
    );
  }
}
